---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: weather
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: weather
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: <host>
    path: <mountpath>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: weather
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: weather
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:12.3-alpine
          name: postgres
          env:
            - name: POSTGRES_USER
              value: <username>
            - name: POSTGRES_DB
              value: <dbname>
            - name: POSTGRES_PASSWORD
              value: <password>
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /va/lib/postgresql/data
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    create table weathers (
        location varchar(100) not null,
        weather varchar(100) not null,
        temperature double precision,
        clouds integer,
        wind double precision,
        wind_deg integer,
        timestamp timestamp);
